name: Gradle CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 设置JDK11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 设置权限
      run: chmod +x gradlew
    - name: 用Gradle构建
      run: ./gradlew shadowJar
    - name: 更新Jar
      uses: actions/upload-artifact@v1.0.0
      with:
        name: "ColorMirai"
        path: build/libs
